
spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.0.112:3306/interview?useUnicode=true&characterEncoding=utf8
        username: interview
        password: interview
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    type-aliases-package: com.chuisha.interview.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.chuisha.util.ChuishaMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql